In [1]:
import pandas as pd
import geopandas as gpd
import rasterio
from shapely.geometry import Point
import random
import ast

# prendre une cartede plus haute resolution pour plus de pays
world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres')) 
climate_raster = 'map.tif'

In [2]:
import geopandas as gpd

# Path to your shapefile
shapefile_path = 'map/c1976_2000.shp'

# Load the shapefile using GeoPandas
climate_shapefile = gpd.read_file(shapefile_path)

# Step 1: Display the column names to understand what data is available
print("Column Names in the Shapefile:")
print(climate_shapefile.columns)

# Step 2: Check the first few rows to inspect the structure of the data
print("\nFirst few rows of the Shapefile:")
print(climate_shapefile.head())

# Step 3: Check the data types of each column
print("\nData types of each column:")
print(climate_shapefile.dtypes)

# Step 4: (Optional) Describe the numeric columns, if any, to get an overview of the data
print("\nSummary of numeric columns:")
print(climate_shapefile.describe())

# Step 5: (Optional) If you expect a geometry column, check the geometry of the shapefile
print("\nGeometry column (geometries present in the shapefile):")
print(climate_shapefile.geometry)

Column Names in the Shapefile:
Index(['ID', 'GRIDCODE', 'geometry'], dtype='object')

First few rows of the Shapefile:
   ID  GRIDCODE                                           geometry
0   1        62  POLYGON ((-37.50000 83.50000, -38.00000 83.500...
1   2        62  POLYGON ((-29.50000 83.50000, -37.00000 83.500...
2   3        62  POLYGON ((-46.00000 83.00000, -46.00000 83.500...
3   4        62  POLYGON ((-42.50000 83.50000, -39.50000 83.500...
4   5        61  POLYGON ((55.50000 81.00000, 55.50000 81.50000...

Data types of each column:
ID             int64
GRIDCODE       int64
geometry    geometry
dtype: object

Summary of numeric columns:
                ID     GRIDCODE
count  2259.000000  2259.000000
mean   1130.000000    34.093404
std     652.261451    14.642194
min       1.000000    11.000000
25%     565.500000    26.000000
50%    1130.000000    34.000000
75%    1694.500000    43.000000
max    2259.000000    62.000000

Geometry column (geometries present in the shapefile):
0       POLYGON ((-37.50000 83.50000, -38.00000 83.500...
1       POLYGON ((-29.50000 83.50000, -37.00000 83.500...
2       POLYGON ((-46.00000 83.00000, -46.00000 83.500...
3       POLYGON ((-42.50000 83.50000, -39.50000 83.500...
4       POLYGON ((55.50000 81.00000, 55.50000 81.50000...
                              ...
2254    POLYGON ((-59.50000 -73.00000, -59.00000 -73.0...
2255    POLYGON ((168.50000 -76.50000, 168.00000 -76.5...
2256    POLYGON ((-66.00000 -77.00000, -66.50000 -77.0...
2257    POLYGON ((-159.00000 -80.00000, -164.00000 -80...
2258    POLYGON ((-127.00000 -74.00000, -127.00000 -74...
Name: geometry, Length: 2259, dtype: geometry

In [6]:
import geopandas as gpd

# Path to your shapefile
shapefile_path = 'map/c1976_2000.shp'

# Load the shapefile using GeoPandas
climate_shapefile = gpd.read_file(shapefile_path)

# Display the first few rows to understand the structure
print(climate_shapefile.head())

# Since there's no 'country' column, you need to intersect the geometries with a world borders dataset
# You can use a world borders dataset provided by GeoPandas, like "naturalearth_lowres"
world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))

# Ensure both datasets use the same coordinate reference system (CRS)
# Reproject the world data to match the shapefile CRS if needed
if climate_shapefile.crs != world.crs:
    world = world.to_crs(climate_shapefile.crs)

# Perform a spatial join to map climate polygons to countries
# This will give each climate polygon a corresponding country based on spatial intersection
climate_with_countries = gpd.sjoin(climate_shapefile, world, how="inner", op="intersects")

# Now group the data by country and get the unique climate classifications (GRIDCODEs) for each country
climate_per_country = climate_with_countries.groupby('name')['GRIDCODE'].unique()

# Convert to a dictionary for easier access
climate_per_country_dict = climate_per_country.to_dict()

# Display the climate types for each country
for country, climates in climate_per_country_dict.items():
    print(f"Country: {country}, Climate Types: {climates}")

   ID  GRIDCODE                                           geometry
0   1        62  POLYGON ((-37.50000 83.50000, -38.00000 83.500...
1   2        62  POLYGON ((-29.50000 83.50000, -37.00000 83.500...
2   3        62  POLYGON ((-46.00000 83.00000, -46.00000 83.500...
3   4        62  POLYGON ((-42.50000 83.50000, -39.50000 83.500...
4   5        61  POLYGON ((55.50000 81.00000, 55.50000 81.50000...
Country: Afghanistan, Climate Types: [45 47 27 21 34 46 26 62 43 35 32 31 22]
Country: Albania, Climate Types: [42 32 35 34]
Country: Algeria, Climate Types: [27 34 21 26 22]
Country: Angola, Climate Types: [22 27 14 37 38 21]
Country: Antarctica, Climate Types: [61]
Country: Argentina, Climate Types: [38 26 39 27 22 36 21 37 62 35 32 31 33]
Country: Armenia, Climate Types: [41 31 42 26 45]
Country: Australia, Climate Types: [12 14 31 11 37 27 21 32 22 34 35 26]
Country: Austria, Climate Types: [43 42 62 32]
Country: Azerbaijan, Climate Types: [32 42 43 31 26 41 34 45]
Country: Bahamas, Climate Types: [14]
Country: Bangladesh, Climate Types: [12 14 37]
Country: Belarus, Climate Types: [42 32]
Country: Belgium, Climate Types: [32]
Country: Belize, Climate Types: [14 12 11]
Country: Benin, Climate Types: [27 14]
Country: Bhutan, Climate Types: [62 51 38 37]
Country: Bolivia, Climate Types: [12 14 32 11 38 39 62 26 31 21 27 37]
Country: Bosnia and Herz., Climate Types: [31 42 34 32]
Country: Botswana, Climate Types: [22 27]
Country: Brazil, Climate Types: [12 14 11 13 27 37 31 32 38]
Country: Brunei, Climate Types: [11]
Country: Bulgaria, Climate Types: [42 32 31 35 34]
Country: Burkina Faso, Climate Types: [22 27 14]
Country: Burundi, Climate Types: [38 14]
Country: Cambodia, Climate Types: [12 14]
Country: Cameroon, Climate Types: [22 11 27 12 14]
Country: Canada, Climate Types: [61 62 47 43 51 42 33 32 46 41 35 26]
Country: Central African Rep., Climate Types: [27 12 14]
Country: Chad, Climate Types: [22 27 14]
Country: Chile, Climate Types: [22 21 26 62 35 36 33 32]
Country: China, Climate Types: [62 42 43 26 51 41 49 50 21 37 38 39 32 31 12 14]
Country: Colombia, Climate Types: [22 38 27 12 14 11 32 13 35]
Country: Congo, Climate Types: [11 13 12 14]
Country: Costa Rica, Climate Types: [14 12 32 11]
Country: Croatia, Climate Types: [31 35 34 32]
Country: Cuba, Climate Types: [12 14 13]
Country: Cyprus, Climate Types: [34 27]
Country: Czechia, Climate Types: [42 32]
Country: CÃ´te d'Ivoire, Climate Types: [12 14]
Country: Dem. Rep. Congo, Climate Types: [32 12 14 38 11 37]
Country: Denmark, Climate Types: [32]
Country: Djibouti, Climate Types: [27 22]
Country: Dominican Rep., Climate Types: [32 11 12 14 13]
Country: Ecuador, Climate Types: [13 14 12 11 35 27 38 32]
Country: Egypt, Climate Types: [27 21 22]
Country: El Salvador, Climate Types: [14]
Country: Eq. Guinea, Climate Types: [11 12 14]
Country: Eritrea, Climate Types: [22 27 14]
Country: Estonia, Climate Types: [42]
Country: Ethiopia, Climate Types: [37 38 14 27 32 12 35 22 13]
Country: Falkland Is., Climate Types: [62 33]
Country: Fiji, Climate Types: [12 11]
Country: Finland, Climate Types: [62 43 42]
Country: France, Climate Types: [35 33 43 31 34 32 12 11]
Country: Gabon, Climate Types: [11 13 12 14]
Country: Gambia, Climate Types: [14 13 27]
Country: Georgia, Climate Types: [42 31 32 43 62 41]
Country: Germany, Climate Types: [43 62 32]
Country: Ghana, Climate Types: [27 12 14]
Country: Greece, Climate Types: [42 32 31 35 34]
Country: Greenland, Climate Types: [62 61 26]
Country: Guatemala, Climate Types: [14 11 38 12 32]
Country: Guinea, Climate Types: [13 12 14]
Country: Guinea-Bissau, Climate Types: [13 14]
Country: Guyana, Climate Types: [12 14 11]
Country: Haiti, Climate Types: [11 12 14]
Country: Honduras, Climate Types: [11 13 12 31 14]
Country: Hungary, Climate Types: [42 32]
Country: Iceland, Climate Types: [33 62]
Country: India, Climate Types: [42 43 47 31 32 38 26 21 62 51 50 39 27 34 37 14 13 12 22]
Country: Indonesia, Climate Types: [13 12 11 32 14]
Country: Iran, Climate Types: [31 26 45 46 34 27 21 22]
Country: Iraq, Climate Types: [45 46 34 27 22]
Country: Ireland, Climate Types: [32]
Country: Israel, Climate Types: [27 34 22]
Country: Italy, Climate Types: [42 43 62 33 32 35 31 34]
Country: Jamaica, Climate Types: [12 14 11]
Country: Japan, Climate Types: [43 41 42 32 31 37]
Country: Jordan, Climate Types: [21 26 27 34 22]
Country: Kazakhstan, Climate Types: [26 41 42 62 43 46 21 45 47 34]
Country: Kenya, Climate Types: [14 27 22 12 13 35 11 32 38]
Country: Kosovo, Climate Types: [42 32]
Country: Kuwait, Climate Types: [22]
Country: Kyrgyzstan, Climate Types: [26 45 46 42 43 62 47 21]
Country: Laos, Climate Types: [14 12 37]
Country: Latvia, Climate Types: [42 32]
Country: Lebanon, Climate Types: [35 34]
Country: Lesotho, Climate Types: [38 26 32]
Country: Liberia, Climate Types: [12 14]
Country: Libya, Climate Types: [27 34 22]
Country: Lithuania, Climate Types: [42 32]
Country: Luxembourg, Climate Types: [32]
Country: Macedonia, Climate Types: [42 31 32 35]
Country: Madagascar, Climate Types: [14 12 38 32 31 37 11 27]
Country: Malawi, Climate Types: [38 37 14 27]
Country: Malaysia, Climate Types: [12 11]
Country: Mali, Climate Types: [22 27 14]
Country: Mauritania, Climate Types: [22 27]
Country: Mexico, Climate Types: [26 35 34 27 21 22 32 38 37 31 14 13 12 11]
Country: Moldova, Climate Types: [42 32 31]
Country: Mongolia, Climate Types: [62 51 26 50 43 21]
Country: Montenegro, Climate Types: [42 31 32 34]
Country: Morocco, Climate Types: [26 27 34 21 22]
Country: Mozambique, Climate Types: [37 27 14 38]
Country: Myanmar, Climate Types: [39 62 38 32 37 14 27 12]
Country: N. Cyprus, Climate Types: [34 27]
Country: Namibia, Climate Types: [22 26 21 27]
Country: Nepal, Climate Types: [38 51 62 37]
Country: Netherlands, Climate Types: [32]
Country: New Caledonia, Climate Types: [13 12 11 14 31]
Country: New Zealand, Climate Types: [33 32 62]
Country: Nicaragua, Climate Types: [11 14 12]
Country: Niger, Climate Types: [22 27 14]
Country: Nigeria, Climate Types: [22 27 12 14]
Country: North Korea, Climate Types: [49 51 42 41 50]
Country: Norway, Climate Types: [61 62 33 42 32 43]
Country: Oman, Climate Types: [22]
Country: Pakistan, Climate Types: [26 62 43 47 46 21 35 42 34 32 31 27 37 22]
Country: Palestine, Climate Types: [27 34]
Country: Panama, Climate Types: [14 12 11]
Country: Papua New Guinea, Climate Types: [11 12 14]
Country: Paraguay, Climate Types: [12 14 27 37 31]
Country: Peru, Climate Types: [14 27 38 32 12 26 22 11 21 62 39]
Country: Philippines, Climate Types: [11 14 38 12 13]
Country: Poland, Climate Types: [42 43 32]
Country: Portugal, Climate Types: [35 34]
Country: Puerto Rico, Climate Types: [11 12 14]
Country: Qatar, Climate Types: [22]
Country: Romania, Climate Types: [43 42 32 26 31]
Country: Russia, Climate Types: [62 44 43 52 48 47 51 42 50 26 49 34 32 41 31]
Country: Rwanda, Climate Types: [14 32 38]
Country: S. Sudan, Climate Types: [12 14 22 27]
Country: Saudi Arabia, Climate Types: [21 22]
Country: Senegal, Climate Types: [22 14 13 27]
Country: Serbia, Climate Types: [31 42 32]
Country: Sierra Leone, Climate Types: [12 14]
Country: Slovakia, Climate Types: [43 42 32]
Country: Slovenia, Climate Types: [42 43 31 32]
Country: Solomon Is., Climate Types: [11]
Country: Somalia, Climate Types: [27 22 13]
Country: Somaliland, Climate Types: [37 27 22]
Country: South Africa, Climate Types: [22 37 26 27 14 32 21 38 31 35 34]
Country: South Korea, Climate Types: [41 42 50 37 49 31]
Country: Spain, Climate Types: [31 34 26 35 32 27]
Country: Sri Lanka, Climate Types: [13 12 11]
Country: Sudan, Climate Types: [14 22 27]
Country: Suriname, Climate Types: [12 11]
Country: Sweden, Climate Types: [62 42 32 43]
Country: Switzerland, Climate Types: [62 43 33 32]
Country: Syria, Climate Types: [26 27 21 35 34 22]
Country: Taiwan, Climate Types: [32 31 37 38 14 12]
Country: Tajikistan, Climate Types: [45 26 35 47 34 21 46 62]
Country: Tanzania, Climate Types: [12 11 32 27 38 13 14 37]
Country: Thailand, Climate Types: [37 12 14 11]
Country: Timor-Leste, Climate Types: [14]
Country: Togo, Climate Types: [14]
Country: Trinidad and Tobago, Climate Types: [12 14]
Country: Tunisia, Climate Types: [34 26 21 27 22]
Country: Turkey, Climate Types: [31 35 32 34 46 41 45 42 26]
Country: Turkmenistan, Climate Types: [34 27 21 26]
Country: Uganda, Climate Types: [32 27 12 13 11 14]
Country: Ukraine, Climate Types: [43 41 32 31 42 26]
Country: United Arab Emirates, Climate Types: [22]
Country: United Kingdom, Climate Types: [33 32]
Country: United States of America, Climate Types: [62 47 43 26 51 33 42 32 46 34 35 49 50 21 41 31 37 27 22 11 14 12]
Country: Uruguay, Climate Types: [32 31]
Country: Uzbekistan, Climate Types: [46 45 47 21 26 35 34 27]
Country: Vanuatu, Climate Types: [11 12]
Country: Venezuela, Climate Types: [22 27 38 12 11 32 14]
Country: Vietnam, Climate Types: [14 37 12]
Country: W. Sahara, Climate Types: [22]
Country: Yemen, Climate Types: [21 27 26 22]
Country: Zambia, Climate Types: [38 14 27 37]
Country: Zimbabwe, Climate Types: [27 14 37 38 22]
Country: eSwatini, Climate Types: [37 27 14 38]

In [7]:
 df =pd.DataFrame([climate_per_country_dict])

In [8]:
df.transpose().to_csv('climate_names.csv')

In [11]:
import pandas as pd
import numpy as np
df = pd.read_csv('climate_names.csv')
df.rename(columns={'Unnamed: 0': 'country'}, inplace=True)
df.rename(columns={'0': 'climate'}, inplace=True)


def climate_to_continuous(koppen_code):
    temperature_map = {
        11: 1.0,  # Af
        12: 0.9,  # Am
        13: 0.8,  # As
        14: 0.7,  # Aw
        21: 0.5,  # BWk
        22: 0.6,  # BWh
        26: 0.3,  # BSk
        27: 0.4,  # BSh
        31: 0.6,  # Cfa
        32: 0.5,  # Cfb
        33: 0.4,  # Cfc
        34: 0.7,  # Csa
        35: 0.5,  # Csb
        36: 0.4,  # Csc
        37: 0.5,  # Cwa
        38: 0.4,  # Cwb
        39: 0.3,  # Cwc
        41: 0.6,  # Dfa
        42: 0.5,  # Dfb
        43: 0.4,  # Dfc
        44: 0.3,  # Dfd
        45: 0.4,  # Dsa
        46: 0.4,  # Dsb
        47: 0.4,  # Dsc
        48: 0.4,  # Dsd
        49: 0.3,  # Dwa
        50: 0.2,  # Dwb
        51: 0.1,  # Dwc
        52: 0.1,  # Dwd
        61: 0.1,  # EF
        62: 0.1   # ET
    }
    
    precipitation_map = {
        11: 1.0,  # Af
        12: 0.9,  # Am
        13: 0.9,  # As
        14: 0.7,  # Aw
        21: 0.1,  # BWk
        22: 0.2,  # BWh
        26: 0.3,  # BSk
        27: 0.4,  # BSh
        31: 0.7,  # Cfa
        32: 0.6,  # Cfb
        33: 0.5,  # Cfc
        34: 0.8,  # Csa
        35: 0.6,  # Csb
        36: 0.5,  # Csc
        37: 0.7,  # Cwa
        38: 0.8,  # Cwb
        39: 0.6,  # Cwc
        41: 0.5,  # Dfa
        42: 0.4,  # Dfb
        43: 0.3,  # Dfc
        44: 0.2,  # Dfd
        45: 0.4,  # Dsa
        46: 0.4,  # Dsb
        47: 0.4,  # Dsc
        48: 0.4,  # Dsd
        49: 0.3,  # Dwa
        50: 0.2,  # Dwb
        51: 0.1,  # Dwc
        52: 0.1,  # Dwd
        61: 0.1,  # EF
        62: 0.1   # ET
    }
    
    seasonality_map = {
        11: 1.0,  # Af
        12: 0.8,  # Am
        13: 0.7,  # As
        14: 0.6,  # Aw
        21: 0.1,  # BWk
        22: 0.1,  # BWh
        26: 0.2,  # BSk
        27: 0.3,  # BSh
        31: 0.6,  # Cfa
        32: 0.5,  # Cfb
        33: 0.4,  # Cfc
        34: 0.5,  # Csa
        35: 0.5,  # Csb
        36: 0.4,  # Csc
        37: 0.5,  # Cwa
        38: 0.4,  # Cwb
        39: 0.3,  # Cwc
        41: 0.5,  # Dfa
        42: 0.4,  # Dfb
        43: 0.3,  # Dfc
        44: 0.3,  # Dfd
        45: 0.4,  # Dsa
        46: 0.4,  # Dsb
        47: 0.4,  # Dsc
        48: 0.4,  # Dsd
        49: 0.3,  # Dwa
        50: 0.2,  # Dwb
        51: 0.1,  # Dwc
        52: 0.1,  # Dwd
        61: 0.1,  # EF
        62: 0.1   # ET
    }
    
    aridity_map = {
        11: 0.1,  # Af
        12: 0.2,  # Am
        13: 0.2,  # As
        14: 0.3,  # Aw
        21: 0.9,  # BWk
        22: 0.8,  # BWh
        26: 0.6,  # BSk
        27: 0.5,  # BSh
        31: 0.5,  # Cfa
        32: 0.5,  # Cfb
        33: 0.4,  # Cfc
        34: 0.4,  # Csa
        35: 0.5,  # Csb
        36: 0.4,  # Csc
        37: 0.3,  # Cwa
        38: 0.2,  # Cwb
        39: 0.2,  # Cwc
        41: 0.3,  # Dfa
        42: 0.4,  # Dfb
        43: 0.4,  # Dfc
        44: 0.3,  # Dfd
        45: 0.4,  # Dsa
        46: 0.4,  # Dsb
        47: 0.4,  # Dsc
        48: 0.4,  # Dsd
        49: 0.3,  # Dwa
        50: 0.3,  # Dwb
        51: 0.1,  # Dwc
        52: 0.1,  # Dwd
        61: 0.1,  # EF
        62: 0.1   # ET
    }
    
    # Convert the code into continuous values using the mappings above
    T = temperature_map.get(koppen_code, np.nan)
    P = precipitation_map.get(koppen_code, np.nan)
    S = seasonality_map.get(koppen_code, np.nan)
    A = aridity_map.get(koppen_code, np.nan)
    
    return {
        'Temperature': T,
        'Precipitation': P,
        'Seasonality': S,
        'Aridity': A
    }

def calculate_average_continuous(climate_codes):
    temperature_list = []
    precipitation_list = []
    seasonality_list = []
    aridity_list = []
    
    for code in climate_codes:
        continuous_values = climate_to_continuous(code)
        
        if not np.isnan(continuous_values['Temperature']):
            temperature_list.append(continuous_values['Temperature'])
        if not np.isnan(continuous_values['Precipitation']):
            precipitation_list.append(continuous_values['Precipitation'])
        if not np.isnan(continuous_values['Seasonality']):
            seasonality_list.append(continuous_values['Seasonality'])
        if not np.isnan(continuous_values['Aridity']):
            aridity_list.append(continuous_values['Aridity'])
    
    avg_temperature = np.nan if not temperature_list else sum(temperature_list) / len(temperature_list)
    avg_precipitation = np.nan if not precipitation_list else sum(precipitation_list) / len(precipitation_list)
    avg_seasonality = np.nan if not seasonality_list else sum(seasonality_list) / len(seasonality_list)
    avg_aridity = np.nan if not aridity_list else sum(aridity_list) / len(aridity_list)
    
    return {
        'Avg_Temperature': avg_temperature,
        'Avg_Precipitation': avg_precipitation,
        'Avg_Seasonality': avg_seasonality,
        'Avg_Aridity': avg_aridity
    }

df['climate'] = df['climate'].apply(lambda x: list(map(int, ast.literal_eval(x.replace(' ', ',')))))
df['Continuous_Climate'] = df['climate'].apply(calculate_average_continuous)

df_expanded = pd.concat([df['country'], df['Continuous_Climate'].apply(pd.Series)], axis=1)

df_expanded

,country,Avg_Temperature,Avg_Precipitation,Avg_Seasonality,Avg_Aridity
0,Afghanistan,0.446154,0.407692,0.338462,0.492308
1,Albania,0.550000,0.600000,0.475000,0.450000
2,Algeria,0.500000,0.360000,0.240000,0.640000
3,Angola,0.516667,0.483333,0.333333,0.500000
4,Antarctica,0.100000,0.100000,0.100000,0.100000
...,...,...,...,...,...
171,W. Sahara,0.600000,0.200000,0.100000,0.800000
172,Yemen,0.450000,0.250000,0.175000,0.700000
173,Zambia,0.500000,0.650000,0.450000,0.325000
174,Zimbabwe,0.520000,0.560000,0.380000,0.420000
175,eSwatini,0.500000,0.650000,0.450000,0.325000

In [22]:
df_expanded.to_csv('climate_in_continuous.csv')